// Generated by scripts/journey-release.mjs; public code fingerprints, never credentials.
export const journeyRelease = {
  "contractVersion": 2,
  "functionsHash": "903ef2f2595e8f529d915978755269b5c9df9815d72e999adae9ccb541af965e",
  "storageRulesHash": "cabe0edda8e862cd1735bcaebdd87d40f141d9619ca5488965472757bf819868"
} as const;
