// Generated by scripts/journey-release.mjs; public code fingerprints, never credentials.
export const journeyRelease = {
  "contractVersion": 2,
  "functionsHash": "6d4c6885d13f5a068c56430ce46da85cce240472b2abfdacdcd24f27e8140a45",
  "storageRulesHash": "cabe0edda8e862cd1735bcaebdd87d40f141d9619ca5488965472757bf819868"
} as const;
