// Generated by scripts/journey-release.mjs; public code fingerprints, never credentials.
export const journeyRelease = {
  "contractVersion": 2,
  "functionsHash": "58047193e160f8f979a62918d149966d96df1e164f48619dd924c5d25221c8f3",
  "storageRulesHash": "cabe0edda8e862cd1735bcaebdd87d40f141d9619ca5488965472757bf819868"
} as const;
